### ISSUE TITLE
Won't complete npm install, missing iotivity node, on raspbian jessie.

### ISSUE THREAD

**Issue by larsdolvik** [01org/iot-rest-api-server#58]
Hi,

When I am trying to npm install the iot-rest-api-server it says I am missing iotivity node. I have tried installing it manually through npm install iotivity-node, but it will not complete. However, I have gotten iotivity-node running through cloning the git repository, but the iot-rest-api-server still will not install. Any ideas as of why it will not install?

OS: Raspbian Jessie
node: 7.5.0
npm: 4.1.2

Compiling out/linux/x86/release/resource/csdk/logger/src/logger.o
gcc: error: unrecognized command line option '-m32'
scons: *** [out/linux/x86/release/resource/csdk/logger/src/logger.o] Error 1
scons: building terminated because of errors.
csdk.target.mk:13: recipe for target 'iotivity-installed' failed
make: *** [iotivity-installed] Error 2
make: Leaving directory '/home/pi/Documents/iot-rest-api-server/node_modules/iotivity-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.34-v7+
gyp ERR! command "/home/pi/.nvm/versions/node/v7.5.0/bin/node" "/home/pi/.nvm/versions/node/v7.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/Documents/iot-rest-api-server/node_modules/iotivity-node
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm ERR! Linux 4.4.34-v7+
npm ERR! argv "/home/pi/.nvm/versions/node/v7.5.0/bin/node" "/home/pi/.nvm/versions/node/v7.5.0/bin/npm" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! iotivity-node@1.2.0-2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iotivity-node@1.2.0-2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iotivity-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iotivity-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iotivity-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Documents/iot-rest-api-server/npm-debug.log

Cheers
larsdolvik

**Comment by qiuzhong** [comment]
> gcc: error: unrecognized command line option '-m32'

Please check the gcc version. Building iotivity-node requires gcc-5 or later, you can refer to the [iotivity-node README](https://github.com/otcshare/iotivity-node).

**Comment by larsdolvik** [comment]
Still getting the same error, even with my gcc and g++ up-to-date.

**Comment by qiuzhong** [comment]
Please read the [iotivity-node README](https://github.com/otcshare/iotivity-node/blob/master/README.md) carefully and make sure these dependent packages are installed: <strong>unzip, git, scons, make, uuid-dev, libglib2.0-dev</strong> and try again.

**Comment by nagineni** [comment]
> Compiling out/linux/x86/release/resource/csdk/logger/src/logger.o
> scons: *** [out/linux/x86/release/resource/csdk/logger/src/logger.o] Error 1

Something wrong with the target arch. It should not be out/linux/x86/ on Raspberry Pi.

**Comment by nagineni** [comment]
Missing arm architecture was added to the archMap in iotivity-node after v1.2.0-2 release.
https://github.com/otcshare/iotivity-node/pull/114

Latest iot-rest-api-server pulls the iotivity-node version which has the fix. @larsdolvik Could you please check this with the latest iot-rest-api-server?
